/*
 * generated by Xtext 2.23.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.WhileLRuntimeModule;
import org.xtext.WhileLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WhileLIdeSetup extends WhileLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WhileLRuntimeModule(), new WhileLIdeModule()));
	}
	
}
