/**
 * generated by Xtext 2.23.0
 */
package org.xtext.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.lggeWhile.Program;
import org.xtext.tests.LggeWhileInjectorProvider;

/* @ExtendWith(/* name is null */)
@InjectWith(LggeWhileInjectorProvider.class)
 */public class LggeWhileParsingTest {
  @Inject
  private /* ParseHelper<Program> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field LggeWhileParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
