/*
 * generated by Xtext 2.23.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalLggeWhileParser;
import org.xtext.services.LggeWhileGrammarAccess;

public class LggeWhileParser extends AbstractAntlrParser {

	@Inject
	private LggeWhileGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLggeWhileParser createParser(XtextTokenStream stream) {
		return new InternalLggeWhileParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public LggeWhileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LggeWhileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
