/*
 * generated by Xtext 2.23.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.LANGAGEWHILE.ui.internal.LANGAGEWHILEActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LggeWhileExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LANGAGEWHILEActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LANGAGEWHILEActivator activator = LANGAGEWHILEActivator.getInstance();
		return activator != null ? activator.getInjector(LANGAGEWHILEActivator.ORG_XTEXT_LGGEWHILE) : null;
	}

}
