/**
 * generated by Xtext 2.23.0
 */
package org.xtext.whileL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.whileL.WhileLPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
} // Command
