/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.Expr;
import org.xtext.example.mydsl.myDsl.ExprBase;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ExprImpl#getExprbase <em>Exprbase</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ExprImpl#getExprbases <em>Exprbases</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprImpl extends ExprBaseImpl implements Expr
{
  /**
   * The cached value of the '{@link #getExprbase() <em>Exprbase</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprbase()
   * @generated
   * @ordered
   */
  protected ExprBase exprbase;

  /**
   * The cached value of the '{@link #getExprbases() <em>Exprbases</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprbases()
   * @generated
   * @ordered
   */
  protected EList<ExprBase> exprbases;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXPR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprBase getExprbase()
  {
    return exprbase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExprbase(ExprBase newExprbase, NotificationChain msgs)
  {
    ExprBase oldExprbase = exprbase;
    exprbase = newExprbase;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR__EXPRBASE, oldExprbase, newExprbase);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExprbase(ExprBase newExprbase)
  {
    if (newExprbase != exprbase)
    {
      NotificationChain msgs = null;
      if (exprbase != null)
        msgs = ((InternalEObject)exprbase).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR__EXPRBASE, null, msgs);
      if (newExprbase != null)
        msgs = ((InternalEObject)newExprbase).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR__EXPRBASE, null, msgs);
      msgs = basicSetExprbase(newExprbase, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR__EXPRBASE, newExprbase, newExprbase));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ExprBase> getExprbases()
  {
    if (exprbases == null)
    {
      exprbases = new EObjectContainmentEList<ExprBase>(ExprBase.class, this, MyDslPackage.EXPR__EXPRBASES);
    }
    return exprbases;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR__EXPRBASE:
        return basicSetExprbase(null, msgs);
      case MyDslPackage.EXPR__EXPRBASES:
        return ((InternalEList<?>)getExprbases()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR__EXPRBASE:
        return getExprbase();
      case MyDslPackage.EXPR__EXPRBASES:
        return getExprbases();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR__EXPRBASE:
        setExprbase((ExprBase)newValue);
        return;
      case MyDslPackage.EXPR__EXPRBASES:
        getExprbases().clear();
        getExprbases().addAll((Collection<? extends ExprBase>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR__EXPRBASE:
        setExprbase((ExprBase)null);
        return;
      case MyDslPackage.EXPR__EXPRBASES:
        getExprbases().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR__EXPRBASE:
        return exprbase != null;
      case MyDslPackage.EXPR__EXPRBASES:
        return exprbases != null && !exprbases.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ExprImpl
