/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lggeWhile;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lggeWhile.Expr#getExprbase <em>Exprbase</em>}</li>
 * </ul>
 *
 * @see org.xtext.lggeWhile.LggeWhilePackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends ExprBase
{
  /**
   * Returns the value of the '<em><b>Exprbase</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.lggeWhile.ExprBase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprbase</em>' containment reference list.
   * @see org.xtext.lggeWhile.LggeWhilePackage#getExpr_Exprbase()
   * @model containment="true"
   * @generated
   */
  EList<ExprBase> getExprbase();

} // Expr
