/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lggeWhile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lggeWhile.Expr#getExprbase <em>Exprbase</em>}</li>
 *   <li>{@link org.xtext.lggeWhile.Expr#getExprbase1 <em>Exprbase1</em>}</li>
 * </ul>
 *
 * @see org.xtext.lggeWhile.LggeWhilePackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
  /**
   * Returns the value of the '<em><b>Exprbase</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprbase</em>' containment reference.
   * @see #setExprbase(ExprBase)
   * @see org.xtext.lggeWhile.LggeWhilePackage#getExpr_Exprbase()
   * @model containment="true"
   * @generated
   */
  ExprBase getExprbase();

  /**
   * Sets the value of the '{@link org.xtext.lggeWhile.Expr#getExprbase <em>Exprbase</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exprbase</em>' containment reference.
   * @see #getExprbase()
   * @generated
   */
  void setExprbase(ExprBase value);

  /**
   * Returns the value of the '<em><b>Exprbase1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprbase1</em>' containment reference.
   * @see #setExprbase1(ExprBase)
   * @see org.xtext.lggeWhile.LggeWhilePackage#getExpr_Exprbase1()
   * @model containment="true"
   * @generated
   */
  ExprBase getExprbase1();

  /**
   * Sets the value of the '{@link org.xtext.lggeWhile.Expr#getExprbase1 <em>Exprbase1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exprbase1</em>' containment reference.
   * @see #getExprbase1()
   * @generated
   */
  void setExprbase1(ExprBase value);

} // Expr
