/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lggeWhile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Base</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lggeWhile.LggeWhilePackage#getExprBase()
 * @model
 * @generated
 */
public interface ExprBase extends EObject
{
} // ExprBase
