/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lggeWhile;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LExpr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lggeWhile.LExpr#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.lggeWhile.LggeWhilePackage#getLExpr()
 * @model
 * @generated
 */
public interface LExpr extends ExprBase
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.lggeWhile.Expr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference list.
   * @see org.xtext.lggeWhile.LggeWhilePackage#getLExpr_Expr()
   * @model containment="true"
   * @generated
   */
  EList<Expr> getExpr();

} // LExpr
