/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lggeWhile;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vars</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lggeWhile.Vars#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see org.xtext.lggeWhile.LggeWhilePackage#getVars()
 * @model
 * @generated
 */
public interface Vars extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute list.
   * @see org.xtext.lggeWhile.LggeWhilePackage#getVars_Var()
   * @model unique="false"
   * @generated
   */
  EList<String> getVar();

} // Vars
