/*
 * generated by Xtext 2.23.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.LANGAGEWHILE.ui.internal.LANGAGEWHILEActivator;

public class LggeWhileUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LANGAGEWHILEActivator.getInstance().getInjector("org.xtext.LggeWhile");
	}

}
