/*
 * generated by Xtext 2.23.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.compwhile.ui.internal.CompwhileActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WhileLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CompwhileActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CompwhileActivator activator = CompwhileActivator.getInstance();
		return activator != null ? activator.getInjector(CompwhileActivator.ORG_XTEXT_WHILEL) : null;
	}

}
