/*
 * generated by Xtext 2.23.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.LggeWhileRuntimeModule;
import org.xtext.LggeWhileStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LggeWhileIdeSetup extends LggeWhileStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LggeWhileRuntimeModule(), new LggeWhileIdeModule()));
	}
	
}
