/**
 * generated by Xtext 2.12.0
 */
package org.xtext;

import org.xtext.LggeWhileStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LggeWhileStandaloneSetup extends LggeWhileStandaloneSetupGenerated {
  public static void doSetup() {
    new LggeWhileStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
